sudo: false
language: python
python:
  - "3.6"
env:
  - CODACY_PROJECT_TOKEN="7254702c94ca4391b0ea3f7c8dae9ae8"

install:
  - "pip install pytest pytest-cov coveralls codacy-coverage"
  - "pip install -r requirements.txt"
#script: coverage run -m unittest discover
script: python -m pytest --cov .
after_success:
  - bash <(curl -s https://codecov.io/bash)

