    openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
      # Both properties are required
      required:  
        - id
        - name



paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
paths:
  /user/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: name
          in: path
          required: true
          description: Id of user to look up.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
                  member_since:
                    type: string
                    format: date-time
                    example: Sat, 15 Sep 2018 14:58:48 -0000
        '404':
          description: User not found.
    delete:
      summery: Delete a user by ID.
      parameters:
        - name: name
          in: path
          required: true
          description: Id of user to delete.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '202':
          description: User deleted.
        '404':
          description: User not found

paths:
  /user/{name}:
    get:
      summary: Returns a user by name.
      parameters:
        - name: name
          in: path
          required: true
          description: Name of user to look up.
          schema:
            type : string
            minimum: 1
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
                  member_since:
                    type: string
                    format: date-time
                    example: Sat, 15 Sep 2018 14:58:48 -0000
        '404':
          description: User not found.
    delete:
      summery: Delete a user by name.
      parameters:
        - name: name
          in: path
          required: true
          description: Name of user to delete.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '202':
          description: User deleted.
        '404':
          description: User not found

